sudo: required
services:
  - docker

before_install:
  - docker build -t gbutchers/docker-react -f Dockerfile.dev .
  
script:
  - docker run gbutchers/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk  
  region: "eu-west-1"
  app: "gleb-docker-react"
  env: "GlebDockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-440130807111"
  bucket_path: gleb-docker-react"
  on:
    branch: master
  access_key_id: $AWS_Access_Key
  secret_access_key:
    secure: "$AWS_Secret_Key"